export interface CheatSheetItem {
  category: "Navigation" | "Editing" | "Git" | "Files" | "Tips"
  command: string
  description: string
  workflow?: string
  mode?: string
  example?: string
}

export const cheatSheetData: CheatSheetItem[] = [
  // LazyVim Core Navigation
  {
    category: "Navigation",
    command: "<Space>h/j/k/l",
    description: "Navigate to Left/Lower/Upper/Right Windows",
    workflow: "Switch between split windows quickly",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "h/j/k/l",
    description: "Move left/down/up/right",
    workflow: "Basic cursor movement in normal mode",
    mode: "Normal, Visual",
  },
  {
    category: "Navigation",
    command: "w/b/e",
    description: "Move to next word/previous word/end of word",
    workflow: "Navigate by word boundaries for faster movement",
    mode: "Normal, Visual",
  },
  {
    category: "Navigation",
    command: "0/$",
    description: "Go to beginning/end of line",
    workflow: "Jump to line boundaries quickly",
    mode: "Normal, Visual",
  },
  {
    category: "Navigation",
    command: "gg/G",
    description: "Go to first/last line of document",
    workflow: "Jump to document boundaries",
    mode: "Normal, Visual",
  },
  {
    category: "Navigation",
    command: "Ctrl-u/Ctrl-d",
    description: "Move up/down by half page",
    workflow: "Scroll through large files efficiently",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "Ctrl-b/Ctrl-f",
    description: "Move up/down by full page",
    workflow: "Navigate through long documents",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "gd",
    description: "Goto Definition",
    workflow: "Jump to function/variable definition using LSP",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "gr",
    description: "Show References",
    workflow: "Find all references to symbol under cursor",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "gI",
    description: "Goto Implementation",
    workflow: "Jump to implementation of interface/abstract method",
    mode: "Normal",
  },

  // LazyVim File Operations
  {
    category: "Files",
    command: "<Space>ff",
    description: "Find Files (Root Dir)",
    workflow: "Open file picker to search and open files in project root",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>fg",
    description: "Find Files (git-files)",
    workflow: "Search only git-tracked files for faster results",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>fr",
    description: "Recent Files",
    workflow: "Quickly access recently opened files",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>fb",
    description: "Find Buffers",
    workflow: "Switch between currently open buffers",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>fn",
    description: "New File",
    workflow: "Create a new file in current directory",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>w",
    description: "Save File",
    workflow: "Save current buffer to disk",
    mode: "Insert, Visual, Normal, Select",
  },
  {
    category: "Files",
    command: "<Space>bd",
    description: "Delete Buffer",
    workflow: "Close current buffer without closing window",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>bo",
    description: "Delete Other Buffers",
    workflow: "Close all buffers except current one",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>e",
    description: "Explorer (root dir)",
    workflow: "Open file explorer in project root directory",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>E",
    description: "Explorer (cwd)",
    workflow: "Open file explorer in current working directory",
    mode: "Normal",
  },

  // LazyVim Editing
  {
    category: "Editing",
    command: "i/a/o/O",
    description: "Insert at cursor/after cursor/new line below/above",
    workflow: "Enter insert mode at different positions",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "I/A",
    description: "Insert at beginning/end of line",
    workflow: "Quick insertion at line boundaries",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "x/dd",
    description: "Delete character/Delete line",
    workflow: "Remove text at cursor or entire line",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "dw/d$",
    description: "Delete word/Delete to end of line",
    workflow: "Delete text from cursor to word end or line end",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "yy/p/P",
    description: "Yank line/Paste after/Paste before",
    workflow: "Copy and paste text efficiently",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "u/Ctrl-r",
    description: "Undo/Redo",
    workflow: "Navigate through edit history",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: ".",
    description: "Repeat last command",
    workflow: "Quickly repeat previous edit operation",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "gcc",
    description: "Comment/uncomment line",
    workflow: "Toggle comment on current line",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "<Space>cf",
    description: "Format Code",
    workflow: "Auto-format current buffer using configured formatter",
    mode: "Normal, Visual",
  },
  {
    category: "Editing",
    command: "<Space>ca",
    description: "Code Action",
    workflow: "Show available LSP code actions for current context",
    mode: "Normal, Visual",
  },
  {
    category: "Editing",
    command: "<Space>cr",
    description: "Rename Symbol",
    workflow: "Rename symbol under cursor across entire project",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "K",
    description: "Show Hover Documentation",
    workflow: "Display documentation for symbol under cursor",
    mode: "Normal",
  },

  // LazyVim Search & Replace
  {
    category: "Editing",
    command: "<Space>sg",
    description: "Grep (Root Dir)",
    workflow: "Search for text across all files in project",
    mode: "Normal",
  },
  {
    category: "Editing",
    command: "<Space>sw",
    description: "Search word under cursor",
    workflow: "Search for current word across project files",
    mode: "Normal, Visual",
  },
  {
    category: "Editing",
    command: "<Space>sr",
    description: "Search and Replace",
    workflow: "Find and replace text across multiple files",
    mode: "Normal, Visual",
  },
  {
    category: "Editing",
    command: "n/N",
    description: "Next/Previous search result",
    workflow: "Navigate through search matches",
    mode: "Normal, Visual, Operator",
  },

  // LazyGit Integration
  {
    category: "Git",
    command: "gg",
    description: "Open LazyGit in current repo",
    workflow: "Launch LazyGit TUI for comprehensive git operations",
    mode: "LazyVim",
  },
  {
    category: "Git",
    command: "<Space>gs",
    description: "Git Status",
    workflow: "View git status and stage/unstage files",
    mode: "Normal",
  },
  {
    category: "Git",
    command: "<Space>gb",
    description: "Git Blame Line",
    workflow: "Show git blame information for current line",
    mode: "Normal",
  },
  {
    category: "Git",
    command: "<Space>gd",
    description: "Git Diff (hunks)",
    workflow: "View git diff for current file or selection",
    mode: "Normal",
  },

  // LazyGit Shortcuts (within LazyGit)
  {
    category: "Git",
    command: "1-5",
    description: "Switch panels (Status/Files/Branches/Commits/Stash)",
    workflow: "Navigate between different LazyGit panels quickly",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "space",
    description: "Stage/unstage file or checkout branch",
    workflow: "Toggle staging status or switch branches",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "a",
    description: "Stage/unstage all files",
    workflow: "Bulk stage or unstage all modified files",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "c",
    description: "Commit staged changes",
    workflow: "Create commit with staged files",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "p/P",
    description: "Push/Pull changes",
    workflow: "Sync with remote repository",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "n",
    description: "Create new branch",
    workflow: "Create and switch to new git branch",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "d",
    description: "Delete branch or discard changes",
    workflow: "Remove branch or discard uncommitted changes",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "M",
    description: "Merge branch",
    workflow: "Merge selected branch into current branch",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "s/S",
    description: "Stash changes/View stash",
    workflow: "Save or restore work-in-progress changes",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "z",
    description: "Undo last commit",
    workflow: "Revert the most recent commit",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "y",
    description: "Copy to clipboard",
    workflow: "Copy commit hash, branch name, or file name",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "e",
    description: "Edit file",
    workflow: "Open selected file in external editor",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "?",
    description: "Show keybinding help",
    workflow: "Display context-sensitive help menu",
    mode: "LazyGit",
  },
  {
    category: "Git",
    command: "q",
    description: "Quit LazyGit",
    workflow: "Exit LazyGit and return to editor",
    mode: "LazyGit",
  },

  // LazyVim Terminal & Toggles
  {
    category: "Files",
    command: "<Space>ft",
    description: "Terminal (Root Dir)",
    workflow: "Open terminal in project root directory",
    mode: "Normal",
  },
  {
    category: "Files",
    command: "<Space>fT",
    description: "Terminal (cwd)",
    workflow: "Open terminal in current working directory",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>ud",
    description: "Toggle Diagnostics",
    workflow: "Show/hide LSP diagnostic messages",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>uf",
    description: "Toggle Auto Format",
    workflow: "Enable/disable automatic code formatting on save",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>ul",
    description: "Toggle Line Numbers",
    workflow: "Show/hide line numbers in editor",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>uw",
    description: "Toggle Word Wrap",
    workflow: "Enable/disable line wrapping for long lines",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>uz",
    description: "Toggle Zen Mode",
    workflow: "Enter distraction-free editing mode",
    mode: "Normal",
  },

  // LazyVim Window Management
  {
    category: "Navigation",
    command: "<Space>-",
    description: "Split Window Below",
    workflow: "Create horizontal split with new window below",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "<Space>|",
    description: "Split Window Right",
    workflow: "Create vertical split with new window to the right",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "<Space>wd",
    description: "Delete Window",
    workflow: "Close current window split",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "<Space>wm",
    description: "Toggle Zoom Mode",
    workflow: "Maximize current window or restore layout",
    mode: "Normal",
  },

  // LazyVim Diagnostics & LSP
  {
    category: "Tips",
    command: "]d/[d",
    description: "Next/Previous Diagnostic",
    workflow: "Navigate through LSP diagnostic messages",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "]e/[e",
    description: "Next/Previous Error",
    workflow: "Jump to next/previous error diagnostic",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "]w/[w",
    description: "Next/Previous Warning",
    workflow: "Jump to next/previous warning diagnostic",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>cd",
    description: "Line Diagnostics",
    workflow: "Show detailed diagnostics for current line",
    mode: "Normal",
  },

  // LazyVim Productivity Tips
  {
    category: "Tips",
    command: "<Space>l",
    description: "Open Lazy Plugin Manager",
    workflow: "Manage LazyVim plugins and configuration",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>L",
    description: "LazyVim Changelog",
    workflow: "View recent LazyVim updates and changes",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>qq",
    description: "Quit All",
    workflow: "Exit Neovim completely",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>ui",
    description: "Inspect Position",
    workflow: "Debug syntax highlighting and treesitter",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "?",
    description: "Buffer Keymaps (which-key)",
    workflow: "Show all available keybindings for current context",
    mode: "Normal",
  },

  // Flash Navigation
  {
    category: "Navigation",
    command: "s",
    description: "Flash Jump",
    workflow: "Quick jump to any visible location with 2-character search",
    mode: "Normal, Visual, Operator",
  },
  {
    category: "Navigation",
    command: "S",
    description: "Flash Treesitter",
    workflow: "Jump to treesitter nodes for precise code navigation",
    mode: "Normal, Visual, Operator",
  },

  // Buffer Navigation
  {
    category: "Navigation",
    command: "[b/]b",
    description: "Previous/Next Buffer",
    workflow: "Cycle through open buffers",
    mode: "Normal",
  },
  {
    category: "Navigation",
    command: "<Space>bb",
    description: "Switch to Other Buffer",
    workflow: "Toggle between current and previous buffer",
    mode: "Normal",
  },

  // Session Management
  {
    category: "Tips",
    command: "<Space>qs",
    description: "Restore Session",
    workflow: "Restore previous editing session with open files",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>ql",
    description: "Restore Last Session",
    workflow: "Quickly restore the most recent session",
    mode: "Normal",
  },
  {
    category: "Tips",
    command: "<Space>qd",
    description: "Don't Save Current Session",
    workflow: "Prevent current session from being saved",
    mode: "Normal",
  },
]
